<!-- [[RARO]]/apps/web-console/src/components/ArtifactViewer.svelte -->
<!-- Purpose: Overlay component for previewing and managing artifacts -->
<!-- Architecture: UI Component -->
<!-- Dependencies: api -->

<script lang="ts">
  import { getArtifactFileUrl, promoteArtifactToLibrary, type ArtifactFile, type ArtifactMetadata } from '$lib/api';
  import { addLog } from '$lib/stores';

  let {
    artifact,
    runMetadata,
    onClose
  }: {
    artifact: ArtifactFile | null;
    runMetadata: ArtifactMetadata | null;
    onClose: () => void;
  } = $props();

  let isPromoting = $state(false);

  function handleOverlayClick(e: MouseEvent) {
    if (e.target === e.currentTarget) {
      onClose();
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      onClose();
    }
  }

  async function handlePromoteToLibrary() {
    if (!artifact || !runMetadata) return;

    isPromoting = true;
    try {
      await promoteArtifactToLibrary(runMetadata.run_id, artifact.filename);
      addLog('SYSTEM', `Promoted ${artifact.filename} to library`, 'IO_OK');
    } catch (err) {
      addLog('SYSTEM', `Failed to promote artifact: ${err}`, 'IO_ERR');
    } finally {
      isPromoting = false;
    }
  }

  function getFileIcon(contentType: string): string {
    if (contentType.includes('image')) return '📊';
    if (contentType.includes('json')) return '📋';
    if (contentType.includes('csv')) return '📈';
    if (contentType.includes('markdown')) return '📝';
    if (contentType.includes('pdf')) return '📄';
    return '📄';
  }

  function formatBytes(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  }

  function formatTimestamp(iso: string): string {
    const date = new Date(iso);
    return date.toLocaleString();
  }

  function isImageType(contentType: string): boolean {
    return contentType.includes('image/png') ||
           contentType.includes('image/jpeg') ||
           contentType.includes('image/svg');
  }

  function isTextType(contentType: string): boolean {
    return contentType.includes('text/') ||
           contentType.includes('json') ||
           contentType.includes('markdown');
  }

  let fileUrl = $derived(artifact && runMetadata ? getArtifactFileUrl(runMetadata.run_id, artifact.filename) : '');
</script>

<svelte:window onkeydown={handleKeydown} />

{#if artifact && runMetadata}
  <div 
    class="overlay" 
    role="dialog" 
    aria-modal="true" 
    tabindex="-1"
    onclick={handleOverlayClick} 
    onkeydown={handleKeydown}
  >
    
    <div class="viewer-container">

      <!-- Header -->
      <div class="header">
        <div class="title-section">
          <span class="icon">{getFileIcon(artifact.content_type)}</span>
          <div class="title-info">
            <h2 class="filename">{artifact.filename}</h2>
            <div class="meta">
              Generated by <strong>{artifact.agent_id}</strong> · {formatBytes(artifact.size_bytes)}
            </div>
          </div>
        </div>
        <button class="btn-close" onclick={onClose} title="Close (Esc)">✕</button>
      </div>

      <!-- Content Preview -->
      <div class="content-area">
        {#if isImageType(artifact.content_type)}
          <!-- Image Preview -->
          <div class="preview-image">
            <img src={fileUrl} alt={artifact.filename} />
          </div>
        {:else if isTextType(artifact.content_type)}
          <!-- Text/Code Preview (iframe for simplicity) -->
          <iframe src={fileUrl} title={artifact.filename} class="preview-text"></iframe>
        {:else}
          <!-- Generic File Preview -->
          <div class="preview-generic">
            <div class="file-icon-large">{getFileIcon(artifact.content_type)}</div>
            <p class="preview-message">Preview not available for this file type</p>
            <p class="preview-hint">{artifact.content_type}</p>
          </div>
        {/if}
      </div>

      <!-- Metadata Panel -->
      <div class="metadata-panel">
        <div class="metadata-grid">
          <div class="metadata-item">
            <span class="metadata-label">Run ID</span>
            <span class="metadata-value" title={runMetadata.run_id}>{runMetadata.run_id.slice(0, 12)}...</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Workflow</span>
            <span class="metadata-value">{runMetadata.workflow_id}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Generated</span>
            <span class="metadata-value">{formatTimestamp(artifact.generated_at)}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Content Type</span>
            <span class="metadata-value">{artifact.content_type}</span>
          </div>
        </div>
      </div>

      <!-- Actions -->
      <div class="actions">
        <a href={fileUrl} download={artifact.filename} class="btn-action primary">
          ⬇ Download
        </a>
        <button
          class="btn-action secondary"
          onclick={handlePromoteToLibrary}
          disabled={isPromoting}
        >
          {#if isPromoting}
            Promoting...
          {:else}
            ⭐ Save to Library
          {/if}
        </button>
        <a href={fileUrl} target="_blank" class="btn-action secondary">
          ↗ Open in New Tab
        </a>
      </div>

    </div>
  </div>
{/if}

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background: rgba(0, 0, 0, 0.8);
    backdrop-filter: blur(8px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    animation: fadeIn 0.2s ease;
  }

  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  .viewer-container {
    width: 90%;
    max-width: 900px;
    max-height: 90vh;
    background: var(--paper-surface);
    border: 2px solid var(--paper-line);
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
    display: flex;
    flex-direction: column;
    animation: slideUp 0.3s var(--ease-snap);
  }

  @keyframes slideUp {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  /* Header */
  .header {
    padding: 20px 24px;
    border-bottom: 1px solid var(--paper-line);
    display: flex;
    align-items: center;
    justify-content: space-between;
    background: var(--paper-bg);
  }

  .title-section {
    display: flex;
    align-items: center;
    gap: 12px;
    flex: 1;
    min-width: 0;
  }

  .icon {
    font-size: 32px;
    flex-shrink: 0;
  }

  .title-info {
    flex: 1;
    min-width: 0;
  }

  .filename {
    font-family: var(--font-code);
    font-size: 16px;
    font-weight: 700;
    color: var(--paper-ink);
    margin: 0 0 4px 0;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .meta {
    font-family: var(--font-code);
    font-size: 11px;
    color: var(--paper-line);
  }

  .btn-close {
    background: transparent;
    border: none;
    font-size: 24px;
    color: var(--paper-ink);
    cursor: pointer;
    padding: 8px;
    line-height: 1;
    transition: opacity 0.2s;
  }

  .btn-close:hover {
    opacity: 0.7;
  }

  /* Content Area */
  .content-area {
    flex: 1;
    overflow: auto;
    background: var(--paper-bg);
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 300px;
  }

  .preview-image {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px;
  }

  .preview-image img {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
    border: 1px solid var(--paper-line);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  }

  .preview-text {
    width: 100%;
    height: 100%;
    border: none;
    background: white;
  }

  .preview-generic {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
    padding: 48px;
    text-align: center;
  }

  .file-icon-large {
    font-size: 64px;
    opacity: 0.5;
  }

  .preview-message {
    font-family: var(--font-code);
    font-size: 14px;
    color: var(--paper-ink);
    margin: 0;
  }

  .preview-hint {
    font-family: var(--font-code);
    font-size: 11px;
    color: var(--paper-line);
    margin: 0;
  }

  /* Metadata Panel */
  .metadata-panel {
    padding: 16px 24px;
    background: var(--paper-surface);
    border-top: 1px solid var(--paper-line);
  }

  .metadata-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 12px;
  }

  .metadata-item {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .metadata-label {
    font-family: var(--font-code);
    font-size: 9px;
    font-weight: 700;
    color: var(--paper-line);
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .metadata-value {
    font-family: var(--font-code);
    font-size: 11px;
    color: var(--paper-ink);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  /* Actions */
  .actions {
    padding: 20px 24px;
    background: var(--paper-bg);
    border-top: 1px solid var(--paper-line);
    display: flex;
    gap: 12px;
    justify-content: flex-end;
  }

  .btn-action {
    padding: 10px 20px;
    font-family: var(--font-code);
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.5px;
    border: none;
    cursor: pointer;
    transition: all 0.2s;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
  }

  .btn-action.primary {
    background: var(--paper-ink);
    color: var(--paper-bg);
  }

  .btn-action.primary:hover {
    opacity: 0.9;
  }

  .btn-action.secondary {
    background: transparent;
    color: var(--paper-ink);
    border: 1px solid var(--paper-line);
  }

  .btn-action.secondary:hover {
    background: var(--paper-line);
  }

  .btn-action:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
