<!-- [[RARO]]/apps/web-console/src/components/sub/ArtifactCard.svelte -->
<script lang="ts">
  import { fade } from 'svelte/transition';
  import { runtimeStore } from '$lib/stores';
  import { USE_MOCK } from '$lib/api';
  import { getMockGeneratedFile } from '$lib/mock-api';

  let { filename, runId }: { filename: string, runId: string } = $props();

  // Construct the URL to the Kernel's file server
  // In mock mode, use the data URL directly
  let src = $derived(
    USE_MOCK
      ? (getMockGeneratedFile(filename) || `/api/runtime/${runId}/files/${filename}`)
      : `/api/runtime/${runId}/files/${filename}`
  );

  let isLoading = $state(true);
  let hasError = $state(false);

  function handleLoad() {
    isLoading = false;
  }

  function handleError() {
    isLoading = false;
    hasError = true;
  }
</script>

<div class="artifact-card" transition:fade={{ duration: 200 }}>
  <!-- Header -->
  <div class="card-header">
    <div class="header-title">
      <span class="icon">▚</span>
      <span>GENERATED_ARTIFACT</span>
    </div>
    <div class="meta-tag">{filename}</div>
  </div>

  <!-- Viewport -->
  <div class="card-viewport">
    {#if isLoading}
      <div class="loading-state">
        <div class="spinner"></div>
        <span>FETCHING_DATA_STREAM...</span>
      </div>
    {/if}

    {#if hasError}
      <div class="error-state">
        <span>ERR_LOAD_FAILED // 404</span>
      </div>
    {:else}
      <!-- Image generated by Agent -->
      <img 
        {src} 
        alt="Agent Output" 
        onload={handleLoad} 
        onerror={handleError}
        class:hidden={isLoading}
      />
    {/if}
  </div>
  
  <!-- Footer / Actions -->
  <div class="card-footer">
    <a href={src} target="_blank" download={filename} class="action-btn">
      DOWNLOAD_ASSET [↓]
    </a>
  </div>
</div>

<style>
  .artifact-card {
    margin: 16px 0;
    border: 1px solid var(--paper-line);
    background: var(--paper-bg);
    border-radius: 2px;
    font-family: var(--font-code);
    overflow: hidden;
    max-width: 100%;
    display: flex;
    flex-direction: column;
    box-shadow: 0 4px 12px rgba(0,0,0,0.05);
  }

  .card-header {
    background: var(--paper-surface);
    border-bottom: 1px solid var(--paper-line);
    padding: 8px 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .header-title {
    font-size: 10px;
    font-weight: 700;
    color: var(--paper-ink);
    display: flex;
    align-items: center;
    gap: 8px;
    letter-spacing: 1px;
  }

  .icon { color: var(--arctic-cyan); }

  .meta-tag {
    font-size: 9px;
    color: var(--paper-line);
    text-transform: uppercase;
  }

  .card-viewport {
    position: relative;
    min-height: 150px;
    /* Technical grid background for the viewport */
    background-image: 
        linear-gradient(var(--paper-line) 1px, transparent 1px),
        linear-gradient(90deg, var(--paper-line) 1px, transparent 1px);
    background-size: 20px 20px;
    background-position: center;
    background-color: color-mix(in srgb, var(--paper-bg), var(--paper-surface) 50%);
    
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 16px;
    opacity: 0.8; /* Subtle grid styling */
  }

  img {
    max-width: 100%;
    height: auto;
    display: block;
    border: 1px solid var(--paper-line);
    box-shadow: 0 8px 24px rgba(0,0,0,0.1);
    background: white; /* Ensure transparency in PNGs looks okay */
  }
  
  img.hidden {
    opacity: 0;
    position: absolute;
  }

  .loading-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 12px;
    color: var(--paper-line);
    font-size: 9px;
    font-weight: 700;
    letter-spacing: 1px;
  }

  .error-state {
    color: #d32f2f;
    font-size: 10px;
    font-weight: 700;
    border: 1px dashed #d32f2f;
    padding: 8px 16px;
    background: rgba(211, 47, 47, 0.05);
  }

  .spinner {
    width: 16px;
    height: 16px;
    border: 2px solid var(--paper-line);
    border-top-color: var(--paper-ink);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  .card-footer {
    padding: 8px;
    border-top: 1px solid var(--paper-line);
    background: var(--paper-surface);
    display: flex;
    justify-content: flex-end;
  }

  .action-btn {
    font-size: 9px;
    font-weight: 700;
    color: var(--paper-ink);
    text-decoration: none;
    padding: 6px 12px;
    border: 1px solid var(--paper-line);
    background: var(--paper-bg);
    transition: all 0.2s;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  .action-btn:hover {
    border-color: var(--paper-ink);
    background: var(--paper-ink);
    color: var(--paper-bg);
  }

  @keyframes spin { to { transform: rotate(360deg); } }
</style>